-- Users: the single shared pool. All apps draw from this table.
CREATE TABLE users (
    id              TEXT        NOT NULL PRIMARY KEY,  -- cuid-style, generated by service
    email           TEXT        NOT NULL UNIQUE,
    name            TEXT,
    password_hash   TEXT,                              -- null for OAuth-only accounts
    avatar_url      TEXT,
    oauth_provider  TEXT,                              -- 'google' | 'github' | null
    oauth_id        TEXT,                              -- provider's user id
    email_verified  INTEGER     NOT NULL DEFAULT 0,    -- boolean
    created_at      TEXT        NOT NULL,              -- ISO-8601 UTC
    updated_at      TEXT        NOT NULL
);

CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_oauth ON users(oauth_provider, oauth_id);
